---
name: Anchore for vulnerability Scanning

on:
  push:
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch: 

jobs:
  test:
    name: Achore scan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - centos
        python-version:
          - 3.8

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build the container image
        run: docker build . --file Dockerfile --tag localbuild/testimage:latest

      - name: Run Trivy vulnerability scanner
        uses: 'aquasecurity/trivy-action@v0.0.8'
        id: scan
        with:
          image-ref: "localbuild/testimage:latest"
          format: 'table'
          # template: '@/contrib/sarif.tpl'
          # output: 'trivy-results.sarif'
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'

     # - name: Upload Trivy scan results to GitHub Security tab
     #   uses: github/codeql-action/upload-sarif@v1
     #   with:
     #     sarif_file: 'trivy-results.sarif'

     # - name: Inspect action SARIF report
     #   run: cat trivy-results.sarif
